[package]
name = "opendp-ffi"
version = "0.1.0"
authors = ["Andrew Vyrros <6577271+andrewvyrros@users.noreply.github.com>"]
edition = "2018"

[dependencies]
opendp = { path = "../opendp" }
lazy_static = "1.4.0"
num = "0.3.1"
backtrace = "0.3"

[lib]
crate-type = ["rlib", "cdylib"]
